version: "3.8"

services:
    # PHP-FPM Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news-aggregator-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: >
            bash -c "
            php artisan migrate --force &&
            php-fpm
            "
        networks:
            - news-aggregator-network

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: news-aggregator-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
        networks:
            - news-aggregator-network

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: news-aggregator-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: news_aggregator
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "33061:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - news-aggregator-network

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: news-aggregator-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - news-aggregator-network

# Docker Networks
networks:
    news-aggregator-network:
        driver: bridge

# Docker Volumes
volumes:
    mysql_data:
